- **File formats** :-
    -
- [Standard way in which data is collected and stored]
    -
    - Most commonly used format for storing data is the spreadsheet format where data is stored in rows and columns
        - Each row is called a record 
        - Each column in a spreadsheet holds data belonging to same data type
        - Commonly used spreadsheet formats are comma separated values and excel sheets
        - Other formats include plain text, json, html, mp3, mp4 etc. 
- Commonly used File
- Read data from 
    - .csv format
        - Comma separated values: - 
            - Removing the extra id column by passing index_col = 0
            - data_csv=pd.read_csv('Iris_data_sample.csv',index_col=0)
            - junk values can be converted to missing values by passing them as a list to the parameter 'na_values'
            - data_csv=pd.read_csv('Iris_data_sample.csv',index_col=0,na_values=["??"])
            - data_csv=pd.read_csv('Iris_data_sample.csv',index_col=0,na_values=["??","###"])
        - Spreadsheet format
        - .csv
        - Each record is separated by comma 
        - Files where records are Separated using a tab are called tab separated values,
        - .csv files can be opened with notepad or microsoft excel

    - .xlsx format
        - Excel spreadsheets :
        - Importing data
            - data_xlsx=pd.read_excel('Iris_data_sample.xlsx',sheet_name='Iris_data')
        - Removing index column and replace '??' and '###' as missing values 
            - data_xlsx=pd.read_excel('Iris_data_sample.xlsx',index_col=0,na_values=["??","###"])
            - part of MS Office 
            - Format - '.xlsx'
    - .txt format
        - Text Format : 
            - data_txt1=pd.read_table('Iris_data_sample.txt')[importing data]
            - Consists of plain text or records 
            - Format '.txt'
            - All columns read stored in a single column of dataframe
            - In order to avoid this, provide a delimiter to the parameters 'sep' or 'delimiter'
        - Defalut delimiter is ttab represented by '\t'
            - data_txt=pd.read_table('Iris_data_sample.txt', sep='\t') is also a parameter who provide parameters to delimiter[seprator]
            - data_txt=pd.read_table('Iris_data_sample.txt', delimiter ="\t") Tab delimiter might not always work
            - Other commonaly used delimiters are commas and blanks - same result 
            - Now if we use a blank as a delimiter then 
            - data_txt1=pd.read_table('Iris_data_sample.txt',delimiter=" ")
    - Text format : - 
            Instead of using read_table(),read_csv() can also be used to read .txt files
            data_txt2=pd.read_csv('Iris_data_sample.txt',delimiter=" ")
        - Remove index column and replace '??' and '###' as missing values
- Importing data into Spyder
    - Importing necessary libraries 
        import os -> to change the working directory 
        import pandas as pd -> to work with dataframes
    - Changing the working directory 
        - os. chdir[chanhing directory] ("C:\pandas") 
    - Importing data 
        - data_csv=pd.read_csv('Iris_data_sample.csv[extension]')
    - Blank celss read as 'nan' [missing values nan for that]

In [29]:
import pandas as pdz

In [30]:
data_txt=pd.read_table('Iris_data_sample.txt')

In [31]:
data_txt1=pd.read_table('Iris_data_sample.txt',delimiter=" ")

In [32]:
data_txt2=pd.read_csv('Iris_data_sample.txt',delimiter=" ")

# Pandas Dataframes I 
- Proviodes high-performance, easy-to-use data structures and analysis tools for the Python programming language
- open source Python library providing high-performance data manipulationans analysis tool using its powerful data structures
- Name pandas is derived from the word Panel Data - an econometricsterm for multidimensional data

## Pandas deals with dataframes
- Name  Dimension       Description
Dataframe   2           2D size mutable
                        potentially heterogeneous tabular data structure with labeled axes(rows and column)
                        goto edit section

### Importing data into Jupyter 
- pandas[Dataframe], numpy[Numerical], matplotlib[Visualization], sklearn[Machine learning]

## Creating copy of Orignal data
There are two ways to create copies
- Shallow copy 
    - Function 
        - samp=cars_data.copy(deep=False),- samp = cars_data
- Description 
    - It only creates a new variables that shares the reference of the orignal object
    - Any changes made to a copy of object will be reflected in the orignal object as well
- Deep copy
    - cars_data1=cars_data.copy(deep=True)
    - in case of deep copy, a copy of object is copied in other object with no refrence to the orignal
    - Any changes  made to copy of object will not be reflected in the orignal object.

In [33]:
import pandas as pd
data_txt=pd.read_table('Iris_data_sample.txt')
data_txt1=pd.read_table('Iris_data_sample.txt',delimiter=" ",index_col=(0))
data_txt2=pd.read_csv('Iris_data_sample.txt',delimiter=" ",index_col=(0))

### Attributes of data

- To get the index(row lables) of the dataframe
    - [DataFrame.index]

- To get the column labels of the dataframe
    - [DataFrame.columns]

- To get the total no of elements from the dataframe
    - [DataFrame.size]

- To get the dimensionality of the dataframe
    - [DataFrame.shape]

- To memory usage of each column in bytes
    - [DataFrame.memory_usage([index,deep])]

- The number of axes / array dimensions
    - [[DataFrame.ndim]]

In [34]:
data_txt.index
# data_txt1.columns
# data_txt2.size
# data_txt2.shape # [row - column]
# data_txt2.memory_usage()
# data_txt2.ndim # 1 dim - row  and other one for column

RangeIndex(start=0, stop=5, step=1)

### Indexing and selecting data
- Python slicing operator '[]' and attribute/dot operator '.' are used for indexing 
- provide quick and easy access to panda data structures
- The Function head returns the first n rows from the dataframe
    - [DataFrame.head([n])]
- The function tail returns the last n rows for the object based on position
    - [DataFrame.tail(n)]
- To access a scalar value, the fastest way is to use the at and iat methods
    - at provides label-based scalar lookups
        - DataType.at[4,'FuelType']
    -iat provides integer-based lookups
        - DataType.iat[5,6]
- To access a group of rows and columns by label(s).loc[] can be used
    - DataType.loc[:,'FuelType'] [: for the all]

In [35]:
data_txt2.head(6) # By default, the head() returns first 5 rows

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,NaN
2,3,????,3.2,one,0.2,Iris-setosa
3,4,??,3.1,1.5,0.2,Iris-setosa
4,5,five,3.6,###,0.2,Iris-setosa

In [36]:
data_txt2.tail(5)

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,NaN
2,3,????,3.2,one,0.2,Iris-setosa
3,4,??,3.1,1.5,0.2,Iris-setosa
4,5,five,3.6,###,0.2,Iris-setosa

In [37]:
data_txt2.at[3,'PetalLengthCm'] # '1.5'
data_txt2.iat[4,5] # 'Iris-setosa'
data_txt2.loc[:,'PetalLengthCm']

0    1.4
1    1.4
2    one
3    1.5
4    ###
Name: PetalLengthCm, dtype: object

# Pandas Dataframes II

- Data Types 
        - The way information gets stored in a dataframe or a python object affects the analysis and outputs of calculation. 
        - Strings are known as objects in pasnds which can store values that contain numbers and / or characters 
    - for example : 'category1'
    - includes integeers and floats
    
    - Numeric Types
        - Pandas and base python uses different names for data types
        - int --- int64  numeric characters
        - float -- float64 -- Numeric characters with decimals
        - '64' simply refers to the memory allocated to store data in each cell which effectively relates to how many digits it can store in each "cell" [64 bits is equivalent to 8 bytes] 
        - Allocating spaces ahead of tims allows computers to optimize storage and processing efficiency.
    
    - character Types
        - Difference b/w category and object
            
            - Category 
                - A string variable consisting of only a few different values. Converting such a string variable to a categorical variable will save some memory 
                - A categorical variable takes on a limited, fixed number of possible values
            
            - Object 
                - The column will be assigned as object data type when it has mixed types (numbers and strings). if a column contains 'nan' (blank cells), pandas will default to object datatypes..
                - For strings, the length is not fixed
    
- Checking data types of each column
    - dtypes returns a series with the data type of each column
        - Syntax : DataFrame.dtypes

- Count of unique data types 
    - get_dtype_counts() returns counts of unique data types in the dataframe
        - Syntax: DataFrame.get_dtype_counts()

- selected data based on data types 
    - pandas.DataFrame.select_dtypes() returns a subset of the cooliumns from dataframe based on the column dtypes
        - Syntax: DataFrame.select_dtypes(include=None, exclude=None)
        
- Concise summary of dataframe
    - info() returns a concise summary of a dataframe
        - data type of index
        - data types of columns
        - count of non-null values
        - memory usage
            Syntax: DataFrame.info()
- Unique elements of columns
    - unique() is used to find the unique elements of a column
        - Syntax : numpy.unique(array)
    - Variable'PetalLengthCm' :
        - print(np.unique(data_txt2['PetalLengthCm']))

In [38]:
data_txt2.dtypes

Unnamed: 0         int64
SepalLengthCm     object
SepalWidthCm     float64
PetalLengthCm     object
PetalWidthCm     float64
Species           object
dtype: object

In [39]:
data_txt2.select_dtypes(exclude=[object])

   Unnamed: 0  SepalWidthCm  PetalWidthCm
0           1           3.5           0.2
1           2           NaN           0.2
2           3           3.2           0.2
3           4           3.1           0.2
4           5           3.6           0.2

In [40]:
data_txt2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     5 non-null      int64
 1   SepalLengthCm  5 non-null      object
 2   SepalWidthCm   4 non-null      float64
 3   PetalLengthCm  5 non-null      object
 4   PetalWidthCm   5 non-null      float64
 5   Species        4 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 452.0+ bytes

In [41]:
import numpy as np
print(np.unique(data_txt2['PetalLengthCm']))

['###' '1.4' '1.5' 'one']

In [42]:
print(np.unique(data_txt2['SepalLengthCm'])) # Special character ?? object  of int64

['4.9' '5.1' '??' '????' 'five']

In [43]:
print(np.unique(data_txt2['PetalWidthCm']))

[0.2]

# Pandas DataFrame III

- Importing data 
    - We need to know how missing values are represented in the dataset in order to make reasonable decision
    - The missing values exist in the from of 'nan' '??' '????'
        - python, by defalut replace blank values with 'nan'
    - Now, importing the data concideering other forms of missing values in a dataframe.
        - data_txt2 = pd.read_csv('Iris_data_sample.csv', index_col=0,na_values=["??","????"])
- Concise summary of dataframe
    - check the screenshot and 
    - data_txt2.info() to check the value after using upper command
- Converting variable's data types
    - astype() method is used to explicity convert data types from one to another 
        - Syntax : DataFrame.astype(dtype)
- Converting 'SepalLengthCm', 'PetalLengthCm' to object data type:
    - data_txt2['SepalWidthCm'] = data_txt2['SepalWidthCm'].astype('object')
    - data_txt2['PetalWidthCm'] = data_txt2['PetalWidthCm'].astype('object'
- Category vs Object data type
    - nbytes() is used to get the total bytes consumed by the elements of the columns
    - Syntax: ndarry.nbytes 
    - if 'SepalWidthCm' is of object data type
        - data_txt2['SepalWidthCm'].nbytes
    - if 'SepalWidthCm' is of category data type,
    - data_txt2['SepalWidthCm'].astype('category').nbytes
- Cleaning column 'Doors
    - checking unique values of variable 'Doors':
        - print(np.unique(data_txt2['PetalWidthCm']))
        - replace() is used to replace a value with the desired value
        - Syntax : DataFrame.replace([to_replace,value,...])
        -   data_txt2['SepalWidthCm'].replace('three',3,inplace=True)
        - try numpy.where()
    - Converting 'Doors' to int64
        - data_txt2['PetalWidthCm']=data_txt2['PetalWidthCm'].astype('int64')
- Getting count of missing values
    - To detect missing values
        - To check the count of missing values present in each column DataFrame.[boolean values]isnull.sum() is used
            - data_txt2.isnull().sum()

In [44]:
import numpy as np
print(np.unique(data_txt1['PetalWidthCm']))

[0.2]

In [45]:
data_txt2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     5 non-null      int64
 1   SepalLengthCm  5 non-null      object
 2   SepalWidthCm   4 non-null      float64
 3   PetalLengthCm  5 non-null      object
 4   PetalWidthCm   5 non-null      float64
 5   Species        4 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 452.0+ bytes

In [46]:
# data_txt2['PetalWidthCm'].replace('three',inplace=True)

In [48]:
data_txt2 = pd.read_csv('Iris_data_sample.csv', index_col=0,na_values=["??","????"])

In [49]:
data_txt2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 1 5.1 3.5 1.4 0.2 "Iris-setosa" to 4 5 5 3.6 ### 0.3 "Iris-setosa"
Empty DataFrame

In [50]:
# data_txt2['SepalWidthCm'] = data_txt2['SepalWidthCm'].astype('object')

In [51]:
data_txt2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 1 5.1 3.5 1.4 0.2 "Iris-setosa" to 4 5 5 3.6 ### 0.3 "Iris-setosa"
Empty DataFrame

In [1]:
# Menubar
#step 1 : import tkinter
from tkinter import *
#step 2: gui interaction
window = Tk()
# step 3 : adding inputs
window.title("simple")
window.geometry("500x500")
menu = Menu(window)
file= Menu(menu, tearoff=0) # tearoff(0 but default it is - 1) use for floating menu over the screen
file.add_command(label="New")
file.add_command(label="Open")
file.add_command(label="Save")
file.add_command(label="Save As")
file.add_separator()
file.add_command(label="Exit", command=window.quit) # to assigned my file in the parent menu
menu.add_cascade(label="File", menu=file)
window.config(menu=menu)
# step 4: main loop
mainloop()